version: '2'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
#      MONGO_DATA_DIR: /data/db
#      MONGO_LOG_DIR:  /dev/null
    volumes:
      - ./.docker/data/db:/data/db
    ports:
      - 47017:27017
    command: mongod --smallfiles --logpath=/dev/null
